# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Pascal Sturmfels
email: your-email@domain.com
github_username: psturmfels
linkedin_username: pascalsturmfels
description: > # this means to ignore newlines until "baseurl:"
  Origami to Computer Science, and everything in between
url: "http://psturmfels.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
