# Site settings
title: Pascal Sturmfels
description: 'Studying computer science at University of Michigan; interests include
machine learning in medicine, approximation algorithms, and iOS development.'

url: 'http://psturmfels.github.io'
baseurl: "/"
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Pascal Sturmfels'
  email: psturm@umich.edu
  #twitter_username: joshgerdes
  facebook_username: psturmfels
  github_username:  psturmfels
  linkedin_username:  pascalsturmfels

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
